### ISSUE TITLE
Hot seems using too much battery

### ISSUE THREAD

**Issue by crizant** [macmade/Hot#27]
<img width="993" alt="螢幕截圖 2021-10-30 下午5 20 22" src="https://user-images.githubusercontent.com/8337876/139539181-9f315b75-e62f-47d6-affa-26d72d9f78d8.png">
The power consumption is more than the electron-based messaging app like WhatsApp and Signal, it is normal?

**Comment by macmade** [comment]
Thanks for the report.  
I'll try to optimize energy consumption for the next release.

**Comment by macmade** [comment]
You can update to version 1.6.0.  
CPU usage has been reduced.

If this is still too high for you, you can also now customize the refresh interval from the app's preferences.

**Comment by crizant** [comment]
Thanks. I will give it a test!

**Comment by Waitsnake** [comment]
I also digged a bit into the issue using instruments tool for profiling the used CPU time.

The most CPU time was used within updateSensors() when removing all sensor menu items and creating them fresh with updated values for each refresh interval. Creating them fresh is time consuming since it creates the icon image fresh via NSImage for each constructor call of SensorViewController class.

I try to optimise this a bit and only creating the sensor menu items the first time this function is called and later just update the text value of each sensor menu item with the new sensor read out. On my M1 machine with 10 CPU sensors it reduces the average CPU time from 4% to 2% when using a refresh interval of 1 second.

Have a look here if you want:
https://github.com/Waitsnake/Hot/commit/b4ed18a7938286d9828b1e76f8804e26945a6a5d

**Comment by Waitsnake** [comment]
I also tried to look into optimisation of ReadM1Sensors(). This time the reducing is not that huge as last optimisation. In sum this change reduces CPU time of ReadM1Sensors() compared to overall CPU time of application from around 66% to 56%. It is not that much but better than nothing.

https://github.com/Waitsnake/Hot/commit/2988589ad1ee1c1b3c4cfd7084277a0bd35357ec

**Comment by Waitsnake** [comment]
I try to optimise ReadM1Sensors() even more and since creation of client and the matching itself used the most CPU time in this function. I changed it in a way that only the first call of ReadM1Sensors() requests client and matching services and saves them for later calls. In sum this change reduces CPU time of ReadM1Sensors() compared to overall CPU time of application from around 56% to 3%.

See here:
https://github.com/Waitsnake/Hot/commit/6d7525b0709bcab8c8774eed3603fd7d97b998a0

After having ReadM1Sensors() a optimised now function main() is the function consuming the most CPU time. But I don't think this can optimised further since this is what calls all the application frameworks and basically draws and handle the application.
