### ISSUE TITLE
M1 Max CPU Temperature is consistently reported 10+˚C colder than other temperature applications

### ISSUE THREAD

**Issue by bnied** [macmade/Hot#35]
As an example, Hot is currently reporting my CPU temperature to be 35˚C:
<img width="62" alt="Screen Shot 2022-01-01 at 8 15 40 AM" src="https://user-images.githubusercontent.com/5209087/147854911-20906b88-4961-449f-bb1c-41a56b78e712.png">

However, both TG Pro and Mx Power Gadget report the CPU temperature as actually being 46˚C:

TG Pro:
<img width="93" alt="Screen Shot 2022-01-01 at 8 16 56 AM" src="https://user-images.githubusercontent.com/5209087/147854926-d24a8e7f-b706-4bc5-993b-b06067388cfd.png">

Mx Power Gadget:
<img width="512" alt="Screen Shot 2022-01-01 at 8 16 59 AM" src="https://user-images.githubusercontent.com/5209087/147854929-511cb5e3-0e79-4148-94a4-36901a6b5d7c.png">

This seems to be limited to my M1 Max, as my M1 Mini does not show the same variance across different temperature apps.

**Comment by Phaoast** [comment]
A similar issue is present on my M1 Pro MacBook Pro

**Comment by NedkoHristov** [comment]
I can agree with @bnied - I've checked on my Mac Air M1 and the temperatures are the same. So it's something M1 MAX related.

**Comment by v3rm0n** [comment]
Trying to understand this issue to provide more info. Can it be that the other apps use SMC for this? I enumerated all T prefixed values and made a list to find that out https://gist.github.com/v3rm0n/7c807a14cee580582cc09a3146a0c13a

**Comment by bnied** [comment]
Another comparison; iStatistica Pro.

M1:
![Image 8-20-22 at 8 27 AM](https://user-images.githubusercontent.com/5209087/185754571-9a5098d8-05c5-43ba-afb5-60f5ddc714e4.jpg)

M1 Max:
<img width="367" alt="Screen Shot 2022-08-20 at 8 25 42 AM" src="https://user-images.githubusercontent.com/5209087/185754587-316f4027-5707-4304-b425-8f2bb22c7b48.png">

My assumption is that the subsequent Mx chips require addressing different sensors (since it looks like M2 support is also broken, see https://github.com/macmade/Hot/issues/41).

**Comment by Barley194** [comment]
Same thing on m1 pro

**Comment by macmade** [comment]
Version 1.7.0 has just been released: https://github.com/macmade/Hot/releases/tag/1.7.0

The names of sensors from the SMC are not documented by Apple, so it's quite difficult to know which is which.
Every Mac also has different sensors.

An M1 MacBook Air has completely different sensors comparing to an M2 MacBook Air, for instance.

With version 1.7.0, you can now choose which sensor to use for the displayed temperature, from the Preferences' window.
You can also choose to display an average temperature, instead of the highest one.
