### ISSUE TITLE
show gpu thermal throttle/clock speed

### ISSUE THREAD

**Issue by morganholly** [macmade/Hot#44]
I've been using Hot for a while now and it's really great, however it would be awesome to get gpu information. I assume gpus do thermal throttle, and mine has def gotten hot enough to cause the cpu to thermal throttle to 50% when it's not doing much. iStatMenus shows the speed but no graph and i can't put it in the menu bar, and Hot seems to be able to differentiate between variable clock speeds that dip under the base rate a little and thermal throttling, which makes it more useful for performance at a glance. If you're able to point me in the right direction I may be able to get it working, but I'm not familiar with the codebase or swift or objective c, and I'm only a little familiar with c.

**Comment by macmade** [comment]
I think this probably goes beyond the scope of this project.

All sensors can be viewed on Apple Silicon, but there's unfortunately no way to tell for sure what the sensor is about.
Same on Intel; sensor names are simply not documented.

**Comment by brunocastello** [comment]
I get your point about the scope, but about not having a way to tell for sure which sensor is which, this seems not to be true, because Sensei app can tell them apart. Check the app and you'll see. I get the point about them not being documented though. The screenshot below shows Sensei Monitor working from the top menubar on my M1 Max Mac Studio:

![Screenshot 2023-01-25 at 7 36 11 PM](https://user-images.githubusercontent.com/23453202/214707461-f7020275-dc5c-47cb-a096-0a09b82e09f6.png)

Other apps like TG Pro, iStat and eul (the last two are also free and on github) can do the same. The competition for them is the Sensei app though.

**Comment by macmade** [comment]
Well I'm currently working on a new version with more sensors.  
I can find the names for some of them, but the issue is that it won't work on all machines, and it's quite hard to maintain.

I'll try to figure out something though...

But to give you an idea, here are all the available temperature sensors on my M2 MacBookAir.  
Note that a different model will have different sensors, with different names.

```
gas gauge battery
NAND CH0 temp
PMU tcal
PMU tdev1
PMU tdev2
PMU tdev3
PMU tdev4
PMU tdev5
PMU tdev6
PMU tdev7
PMU tdev8
PMU tdie1
PMU tdie2
PMU tdie3
PMU tdie4
PMU tdie5
PMU tdie6
PMU tdie7
PMU tdie8
PMU2 tcal
PMU2 tdev1
PMU2 tdev2
PMU2 tdev3
PMU2 tdev4
PMU2 tdev5
PMU2 tdie1
PMU2 tdie2
PMU2 tdie3
PMU2 tdie4
PMU2 tdie5
PMU2 tdie6
PMU2 tdie7
PMU2 tdie8
T5SP
Ta08
Ta09
Ta0C
Ta0D
TAOL
TB0T
TB1T
TB2T
TCHP
TCMb
TCMz
TDBP
TDeL
Te04
Te05
Te06
Tg0e
Tg0f
Tg0m
Tg0n
Tg0q
Tg0r
Th04
Th05
Th06
Th08
Th09
Th0A
Th0C
Th0D
Th0E
Th0G
Th0H
Th0I
Th0K
Th0L
Th0M
TH0T
TH0x
TIOP
Tm0B
TMVR
Tp00
Tp01
Tp02
Tp04
Tp05
Tp06
Tp08
Tp09
Tp0A
Tp0a
Tp0b
Tp0C
Tp0c
Tp0D
Tp0E
Tp0e
Tp0f
Tp0g
Tp0i
Tp0j
Tp0k
Tp0m
Tp0n
Tp0o
Tp0q
Tp0r
Tp0s
TPD0
TPD1
TPD2
TPD3
TPD4
TPD5
TPD6
TPD7
TPDX
TPMP
TPSP
TRD0
TRD1
TRD2
TRD3
TRD4
TRD5
TRD6
TRD7
TRDX
Ts0a
Ts0b
Ts0c
Ts0K
Ts0L
Ts0M
Ts0O
Ts0P
Ts0Q
Ts0S
Ts0T
Ts0U
Ts0W
Ts0X
Ts0Y
Ts1P
TSCD
TsOP
TVA0
TVD0
TVM0
TVM1
TVM2
TVM3
TVS0
TVS1
TVSx
TW0P
Tz11
Tz12
Tz13
Tz14
Tz15
Tz16
Tz17
Tz18
Tz1j
```

**Comment by macmade** [comment]
About competition, I don't think there's room for comparison here.

Sensei, TG Pro, iStats Menu are commercial products.  
This is a free and OpenSource project, maintained only by myself, when I have some free time during the weekends.

Contributions are welcome that being said...
