### ISSUE TITLE
M1 Pro, updated from 1.8.x to 1.9.1, temps now reading much higher

### ISSUE THREAD

**Issue by vmarks** [macmade/Hot#61]
* M1 Pro, MacBook Pro 18,3
* previously running Hot 1.8.x, updated to 1.9.0, and then immediately to 1.9.1.
* previously, temps were 30-34 C. Since updating, they are now reading 56-72 C

I am unsure what changed - was it reading a different sensor before? I always used defaults, and have not changed what sensor was being read.

When I view all sensors, PMU tcal is currently 55c, PMU Tdev is 37, depending on which Tdev is being read (5 is 31C)

I liked the lower temp numbers and was reassured by them. These higher temps make me concerned something is off, especially when Hot always reported lower numbers in the past.

**Comment by m0n0rga** [comment]
I have the same issue

**Comment by macmade** [comment]
Version 1.8.0 introduced support for more temperature sensors, so this is actually expected.

**Long story**:

The first Apple Silicon hardware model was the MacBook Air M1, which I used to add support for Apple Silicon.  
This machine exposed temperature sensors via an interface called `IOHID`.

The later models (M1 MBPro and M2), while still exposing some sensors via `IOHID`, did not include all available sensors, for some reason.

I was able to query another interface called `SMC` to get more sensors on these models.  
This is why the reported temperature is higher in version 1.8.0 and later - it's simply because it's reading more sensors.
