### ISSUE TITLE
Nothing reported on M1 Mac mini

### ISSUE THREAD

**Issue by BrokenHope** [macmade/Hot#8]
I assumed having Apple Silicon support that this would actually work on a M1 based Mac but I get nothing, no CPU temperature or anything. Is this correct?

**Comment by macmade** [comment]
Yes, I observed the same on my development toolkit.  
I haven't been able to test on the final hardware, as I don't have one for the moment.

Temperature sensors may unfortunately be machine specific, and are not documented by Apple in any way.  
I'll see if I can find anything in order to make this work, but it might take some time.

That being said, you probably don't need this app with an M1 Mac Mini. ; )  
I tested the app on an Intel Mini, and I never observed any kind of thermal throttling, even with an Intel chip.   
So, lucky for you, I highly doubt you'll be ever concerned by CPU throttling.

Congratulations on your M1 Mac acquisition!

**Comment by tjluoma** [comment]
Might want to add a comment on the front page that this is only for Intel processors.

**Comment by leehauser** [comment]
I'm not getting any report either on the M1 Mac Air either. I wasn't so much worried about it throttling as I was curious about the actual stats.

**Comment by koenikova** [comment]
> Might want to add a comment on the front page that this is only for Intel processors.

+1

@macmade the reason why I personally am very interested in this tool, is that I have a MacBook Air M1. It is blazingly fast, can work at least 10 hrs full throttle without being plugged in. It is awesome. But.... I have experienced two times in the following setup that it froze (until it cooled off again): 
- 4K monitor plugged in
- some externer HD and SSD's plugged in
- 40 tabs Chrome open
- Video playback VLC
- Spotify
- Discord open
- 3D software with large file open 
- Playing a full-screen game on the 4K display for about 3 hrs (until it froze)

If I would have seen in the menubar that my computer was getting hot, that would have made me turn on an actual fan behind the computer to cool it off a bit. 

Could you use this info to pull the M1 temp sensors?
https://github.com/fermion-star/apple_sensors

If so, one feature which would really be great is adding a 'notification' of any sort when the temperature  reaches a certain threshold for example. 

Thanks for taking the time to read this and happy new year! 👍

**Comment by calvinbradshaw** [comment]
Confirming nothing reported on a MacBook Air M1.  Would be great if it could work with Mac M1.
Thanks!

**Comment by eddideku** [comment]
I read an article about this app that stated quote, "With an app like Hot, you can at least see for yourself what’s going on and hopefully measure much less CPU throttling on these new M1 Mac system"

Very misleading article. Does not work for M1 Macbook Pro.

**Comment by lbibass** [comment]
Could it be feasible to ues the Powermetrics tool to monitor CPU frequency and load as well?

**Comment by themak1985** [comment]
So this is not M1 compatible?

**Comment by macmade** [comment]
Apple Silicon (M1) support has just been added in version 1.3.0: https://github.com/macmade/Hot/releases/tag/1.3.0
